Console.Clear();
Console.Beep(3000,100);
await Task.Delay(1000);
Console.Beep(2000,100);
Console.Beep(1000,100);
Console.ReadKey(true);
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("salam mikonam va khosh omad migm  :))))))");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.Blue; 
Console.WriteLine("dro baraton baz mikonam");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("befarmayid to rahat bashid");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("inja baraye hameh hast");
await Task.Delay(5000);
Console.Clear();
Console.Beep(3000,100);
await Task.Delay(1000);
Console.Beep(2000,100);
Console.Beep(1000,100);
Console.ReadKey(true);
Console.ForegroundColor=ConsoleColor.White;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine ("mano mohadeseh seda mikonan az bachegi hamineh  ^ _^");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("bist sal daram va hanoz koli harf daram");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("to hamedan bozorg shodam va behesh eftekhar mikonam");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.White;
Console.BackgroundColor=ConsoleColor.Yellow;
Console.WriteLine("sobha beh sakhti bidar misham ~_~");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("saat ba sedaye boland zang mizaneh");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("gushimo khamush mikonam va pato ro mikesham ro saram va dobareh miram toyeh khab kotah");
await Task.Delay(5000);
Console.Clear();
Console.Beep(3000,300);
await Task.Delay(2000);
Console.Beep(5000,200);
Console.Beep(2000,100);
await Task.Delay(2000);
Console.Beep(1000,100);
Console.Beep(2000,100);
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("har ruz kod mizanam va omidvaram");
Console.WriteLine("gahi kod kar nemikonad va naomid misham");
await Task.Delay(5000);
Console.WriteLine("yek saat donbal dalilesh migardam");
Console.WriteLine("akharesh ham mibinam khodam moshekl bodam");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.White;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("yek kargah honari mikham besazam  *_*");
Console.WriteLine("daresho hamishe baz mizaram");
await Task.Delay(5000);
Console.WriteLine("harkas miyad bayad yek samboseh biareh");
Console.WriteLine("in tanha ghanon seft va sakht kargah mohadeseh ast");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.White;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("shoaram:aval kod bezan bad negaran sho!     ((((*o*)))");
await Task.Delay(5000);
Console.Clear();
Console.Beep(10000,100);
Console.Beep(5000,200);
await Task.Delay(1000);
Console.Beep(1000,300);
Console.ForegroundColor=ConsoleColor.White;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("ghaza mipazam bo rah mifteh");
Console.WriteLine("boosh ta kucheh baghli mireh");
await Task.Delay(5000);
Console.WriteLine("hamsayeh bi khabar dar mizaneh va ghablameh khalisho dastesh gerefteh  (^ 3 ^ *)");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("ba koli zogh yek labas midozam ");
Console.WriteLine("andazash dorost darnemyad esmesho mizarammodel jadid");
Console.WriteLine("hameh ham bavar mikonan va tarif mikonan  (* o* ) ");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("ba deght aroosk misazam");
Console.WriteLine("cheshmash gerd va bozorg az ab darmyad");
Console.WriteLine("yeki mifahmeh va mikhandeh va man enkar mikonam va rad misham  (^_^)");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("zarf haye geli va ba hoseleh rang mizanam va dastam aslan nemilarzad");
Console.WriteLine("saat ha bi shekayat vaght mizaram");
Console.WriteLine("akharsh yek chiz ghashang padid miavaram  (^.^)");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.Yellow;
Console.WriteLine("sedaye sorfeh az yek gusheh mishnavam sari az jam miparam");
Console.WriteLine("bedon moatali komak miresonam");
Console.WriteLine("badesh tazeh nafas rahat mikesham   (((((-: ");
await Task.Delay(6000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("ro sahneh ba etemad beh nafs miram va naqshmo ba joon va del bazi mikonam va az in kar koli kif mikonamn ");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("baraye chand daghigheh yek ja vaisam cheshmam bi ejazeh basteh misheh");
Console.WriteLine("sarapa va bi seda beh khab miram hich kas ham motavajeh nemisheh  (@_@)");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.Yellow;
Console.WriteLine("gereh haye sakht ra baz mikonam rah hal ra zud pieda mikonam");
Console.WriteLine("moshekl baqieh ra ba aramesh hal mikonam mal khodam ra mizaram vaseh bad (T_T)");
await Task.Delay(5000);
Console.Clear();
Console.Beep(6000,300);
await Task.Delay(1000);
Console.Beep(3000,600);
Console.Beep(2000,800);
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("beh hameh ba yek mil komak mikonam");
Console.WriteLine("ba hoseleh beh harf ha gush midam va ta akharesh kenar adma mimonam  *_*");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("har kasio rahat mikhandonam khodamam ba harf haye khodam mikhandam =))))))))))))))))");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("sovalaye zyadi miporsam va ba konjkavi chizaye jadid ra emtahan mikonam");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.White;
Console.WriteLine("rahat mibakhsham va baraye kasi kam nemizaram va hesab va ketab negah nemidaram ;(");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Red;
Console.BackgroundColor=ConsoleColor.Black;
Console.WriteLine("vaghti gul midam ta akharsh paye harfam mimonam hata agar rah sakhti jelom basheh  (-; ");
await Task.Delay(6000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.Black;
Console.WriteLine("shaba bidar mimonam va ba khial asodeh fekr mikonam");
Console.WriteLine("hamon moqe hast keh chizi kashf mikonam (*^.^*)");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Black;
Console.WriteLine("vaghti kari ra dost daram ta akharsh edameh midam va bad har shkast dobareh talash mikonam ;))))");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("sai mikonam khodam karamo anjam bedam va komak gereftan baram sakhteh");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("harf haye mohem ra to delam negah midaram va rajeb anha fekr mikonam");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("kado haye sadeh mano khili khoshhal mikoneh (;@-_-@)");
await Task.Delay(5000);
Console.Clear();
Console.Beep(6000,400);
await Task.Delay(1000);
Console.Beep(7000,300);
Console.Beep(2000,100);
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.Yellow;
Console.WriteLine("ketab haye zyadi to ghafaseh michinam ba lezat negaheshoon mikonam va hamin baes aramesham misheh ;))))) ");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("samboseh dagh mikharam va ba khordanesh labkhand rezayat mizanam :))))");
Console.WriteLine("ghahveh keh hamisheh dost va nejat dahandeh man az khastegi ast;)))");
await Task.Delay(5000);
Console.Clear();
Console.Beep(3000,200);
await Task.Delay(1000);
Console.Beep(6000,700);
Console.Beep(5000,800);
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("******beh name :mohadeseh ******");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Blue;
Console.BackgroundColor=ConsoleColor.Red;
Console.WriteLine("laghab :malakeh samboseh va estedad parakandeh");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Yellow;
Console.BackgroundColor=ConsoleColor.Black;
Console.WriteLine("agar ta inja hamrah man bodin momnunam azton");
Console.WriteLine("hameh yek samboseh dagh mehmonen mam hastid");
await Task.Delay(5000);
Console.Clear();
Console.ForegroundColor=ConsoleColor.Black;
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("khili khoshhal shodam az ashenayi ba shma  :)))))");
Console.WriteLine("khodahafez");
await Task.Delay(5000);
Console.Clear();
Console.Beep(3000,400);
Console.Beep(2000,100);
await Task.Delay(1000);
Console.Beep(6000,800);
Console.ResetColor();
Console.Clear();